# Generated by Django 4.2.6 on 2024-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
