# Generated by Django 4.2.6 on 2024-08-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salesreportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
    ]
