# Generated by Django 4.2.6 on 2024-08-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sale_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('days_valid', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem')),
                ('sales_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.salesproduct')),
            ],
        ),
    ]
