# Generated by Django 4.2.6 on 2024-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salesproduct_selectedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='days_valid_unit',
            field=models.CharField(default='days', max_length=100),
        ),
    ]
