# Generated by Django 4.2.6 on 2024-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_salesproduct_days_valid_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='item_type',
            field=models.CharField(choices=[('computer_accessory', 'Computer Accessory'), ('security_accessory', 'Security Accessory')], default='computer_accessory', max_length=20),
        ),
    ]
